options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/sleepr-464709/auth/production', '-f', 'apps/auth/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/sleepr-464709/auth/production']

  # Reservations Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/sleepr-464709/reservations/production', '-f', 'apps/reservations/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/sleepr-464709/reservations/production']

  # Payments Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/sleepr-464709/payments/production', '-f', 'apps/payments/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/sleepr-464709/payments/production']

  # Notifications Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/sleepr-464709/notifications/production', '-f', 'apps/notifications/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/sleepr-464709/notifications/production']

