services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3037:3037"
      - "9229:9229"  # Debug port
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3036:3036"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - "3031:3031"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo

