apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/sleepr-464709/payments/production
        name: payments
        env:
          - name: PORT
            value: '3001'
          - name: NOTIFICATION_SERVICE_HOST
            value: notifications
          - name: NOTIFICATION_SERVICE_PORT
            value: '3000'
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: secretKey
        ports:
          - containerPort: 3001

