apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reservations
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/sleepr-463812/reservations/reservations
        name: reservations
